[theme]
primaryColor = "#F94144"     # Rojo vibrante
backgroundColor = "#FFFFFF"   # Fondo blanco
secondaryBackgroundColor = "#F0F2F6" # Gris claro para contenedores
textColor = "#000000"         # Texto principal negro
font = "sans serif"

[server]
enableCORS = false